name: mindboggle-env
channels:
    - clinicalgraphics
dependencies:
    - python=3.5.1
    - vtk=7.0.0
    #-------------------------------------------------------------------------
    # nipype:
    #-------------------------------------------------------------------------
    - scipy
    - networkx
    - lxml
    - simplejson
    - future
    - nose
    - pip
    - pip:
        - nibabel
        - prov
        - traits
        - xvfbwrapper
        - https://github.com/nipy/nipype/archive/master.zip
    #-------------------------------------------------------------------------
    # mindboggle's remaining dependencies:
    #-------------------------------------------------------------------------
    - cmake
    - matplotlib
    - numpy
    - pandas
    #-------------------------------------------------------------------------
    # additional testing tools for circleci.com:
    #-------------------------------------------------------------------------
    - ipython
    - pytest
    - coverage

